#!/usr/bin/env python3
"""Build questions/banks.js from the per-topic JSON files.

The JSON files under questions/ are the human-editable source of truth. The app
loads a single generated JS file (questions/banks.js) so it works when opened
directly from the filesystem, without a web server. Run this after editing any
bank:  python3 build.py
"""
import json
import glob
import os

HERE = os.path.dirname(os.path.abspath(__file__))
QDIR = os.path.join(HERE, "questions")
ORDER = ["upper-gi", "lower-gi", "neoplasms-cancer", "neuro",
         "med-surg-anemia", "med-surg-lower-gi", "med-surg-kidney",
         "med-surg-endocrine"]


def normalize(q, topic, idx):
    """Return a question with one explanation per option, in option order."""
    opts = q["options"]
    ans = q["answer"]
    inc = q["rationale"]["incorrect"]
    is_sata = q.get("type") == "sata"

    if len(inc) == len(opts):
        # Already one entry per option (SATA and "needs teaching" items).
        explanations = list(inc)
    elif not is_sata and len(inc) == len(opts) - 1:
        # Standard multiple choice: reinsert the correct rationale at the key.
        explanations = list(inc)
        explanations.insert(ans, q["rationale"]["correct"])
    else:
        raise ValueError(
            f"{topic}[{idx}]: {len(inc)} rationales for {len(opts)} options "
            f"(sata={is_sata}) — cannot map to options"
        )

    out = {"stem": q["stem"], "options": opts, "answer": ans,
           "explanations": explanations}
    if is_sata:
        out["type"] = "sata"
    return out


def main():
    banks = {}
    labels = {}
    files = sorted(glob.glob(os.path.join(QDIR, "*.json")),
                   key=lambda f: ORDER.index(os.path.splitext(os.path.basename(f))[0])
                   if os.path.splitext(os.path.basename(f))[0] in ORDER else 999)
    for path in files:
        data = json.load(open(path))
        topic = data["topic"]
        labels[topic] = data["label"]
        banks[topic] = [normalize(q, topic, i) for i, q in enumerate(data["questions"])]

    payload = {"labels": labels, "banks": banks}
    out = os.path.join(QDIR, "banks.js")
    with open(out, "w") as f:
        f.write("// Generated by build.py — do not edit. Source: questions/*.json\n")
        f.write("window.NCLEX_DATA = ")
        json.dump(payload, f, ensure_ascii=False, indent=2)
        f.write(";\n")

    total = sum(len(v) for v in banks.values())
    print(f"Wrote {out}: {total} questions across {len(banks)} topics.")


if __name__ == "__main__":
    main()
