// Generated by build.py — do not edit. Source: questions/*.json
window.NCLEX_DATA = {
  "labels": {
    "upper-gi": "Upper GI",
    "lower-gi": "Lower GI",
    "neoplasms-cancer": "Neoplasms & Cancer",
    "neuro": "Migraine · Insomnia · Seizures"
  },
  "banks": {
    "upper-gi": [
      {
        "stem": "A client reports burning epigastric pain that occurs 2-3 hours after eating and is relieved by food or antacids. The nurse recognizes these findings as characteristic of which condition?",
        "options": [
          "Gastric ulcer",
          "Duodenal ulcer",
          "Gastroesophageal reflux disease",
          "Acute gastritis"
        ],
        "answer": 1,
        "explanations": [
          "Gastric ulcer pain is worsened by food and typically occurs about 30-60 minutes after eating due to acid secretion stimulated by food.",
          "Duodenal ulcer pain typically occurs 2-3 hours after eating and is relieved by food or antacids because food absorbs the acid that irritates the ulcerated duodenum.",
          "GERD presents with heartburn and regurgitation within 30-60 minutes of eating, often worsened by lying down.",
          "Acute gastritis presents with upset stomach, burning pain, nausea/vomiting, and is often self-limited."
        ]
      },
      {
        "stem": "A client with peptic ulcer disease presents with black, tarry stools. The nurse documents this finding as which term?",
        "options": [
          "Hematochezia",
          "Hematemesis",
          "Melena",
          "Occult bleeding"
        ],
        "answer": 2,
        "explanations": [
          "Hematochezia is bright red blood per rectum (BRBPR), indicating rapid bleeding that is too fast to be digested—characteristic of lower GI bleeds.",
          "Hematemesis is vomiting blood, which can appear red (fresh) or coffee-ground (digested).",
          "Melena refers to black, tarry stools caused by digested blood from an upper GI bleed. The blood has been in the GI tract long enough to be broken down.",
          "Occult bleeding is hidden blood not visible to the eye, detected only by stool testing."
        ]
      },
      {
        "stem": "A nurse is teaching a client prescribed omeprazole for GERD. Which instruction should the nurse include?",
        "options": [
          "Take the medication as needed when heartburn occurs",
          "Take the medication with food to reduce stomach upset",
          "Take the medication on an empty stomach before meals",
          "Expect immediate relief of symptoms after the first dose"
        ],
        "answer": 2,
        "explanations": [
          "PPIs are NOT PRN medications—they must be taken consistently and take several days to achieve full effect.",
          "PPIs should be taken on an empty stomach, not with food, for best absorption.",
          "PPIs like omeprazole should be taken on an empty stomach before meals for optimal absorption and effectiveness. They work by blocking the proton pump in parietal cells.",
          "PPIs do not provide immediate relief; symptom improvement takes 2-3 days and the typical course is at least 2 weeks."
        ]
      },
      {
        "stem": "A nursing home resident has been taking omeprazole for 3 years. The nurse notes the client has developed a new Clostridioides difficile infection. Which factor most likely contributed to this infection?",
        "options": [
          "The medication caused direct bacterial overgrowth",
          "Long-term acid suppression reduced the stomach's natural defense against pathogens",
          "The medication is contaminated with C. difficile spores",
          "Omeprazole interferes with antibiotic effectiveness"
        ],
        "answer": 1,
        "explanations": [
          "PPIs do not directly cause bacterial overgrowth—they reduce the acid barrier that normally kills pathogens.",
          "Stomach acid is a natural barrier against ingested pathogens. Long-term PPI use significantly reduces acid, making the stomach environment more favorable for pathogens like C. difficile to survive and colonize the GI tract.",
          "Medications are not contaminated with C. difficile; the infection occurs due to reduced gastric acid defense.",
          "PPIs do not interfere with antibiotic effectiveness; the mechanism is acid suppression reducing natural pathogen defense."
        ]
      },
      {
        "stem": "A client with a gastric ulcer is prescribed sucralfate. Which statement by the client indicates correct understanding of the medication?",
        "options": [
          "I will take this medication with my antacid for better effect",
          "I will take this medication one hour after meals",
          "I will take this medication on an empty stomach before eating",
          "I will take this medication at bedtime with a glass of milk"
        ],
        "answer": 2,
        "explanations": [
          "Sucralfate should NOT be taken with antacids. Antacids raise pH, but sucralfate needs acid to activate and form its protective barrier.",
          "Taking after meals is incorrect—sucralfate must be taken before eating on an empty stomach.",
          "Sucralfate should be taken on an empty stomach before eating. It needs an acidic environment to work—it forms a protective paste that coats the ulcer like a bandage.",
          "Milk would raise gastric pH and neutralize the acid sucralfate needs to activate and form its protective barrier. Sucralfate is dosed on an empty stomach before meals and at bedtime, but it should not be taken with milk or antacids."
        ]
      },
      {
        "stem": "A nurse is caring for a client taking long-term NSAIDs for rheumatoid arthritis. Which medication would the nurse expect to be prescribed for ulcer prophylaxis?",
        "options": [
          "Sucralfate",
          "Misoprostol",
          "Aluminum hydroxide",
          "Cimetidine"
        ],
        "answer": 1,
        "explanations": [
          "Sucralfate treats existing ulcers by coating them but is not the first-line prophylaxis for NSAID-induced ulcers.",
          "Misoprostol is a prostaglandin analogue specifically approved for preventing NSAID-induced ulcers. It suppresses acid secretion while increasing protective mucus in the GI tract.",
          "Aluminum hydroxide is an antacid for short-term symptom relief, not ulcer prophylaxis.",
          "H2 blockers like cimetidine may be used but misoprostol is specifically indicated for NSAID-related ulcer prevention."
        ]
      },
      {
        "stem": "A nurse is reviewing medications with a female client of childbearing age who has been prescribed misoprostol. Which statement is most important for the nurse to make?",
        "options": [
          "This medication may cause diarrhea as a side effect",
          "Take this medication with food to reduce stomach upset",
          "You must use reliable contraception while taking this medication",
          "Report any signs of constipation to your provider"
        ],
        "answer": 2,
        "explanations": [
          "While diarrhea can occur, the pregnancy contraindication is the priority safety concern.",
          "This is general advice but not the most critical teaching point for this high-risk medication.",
          "Misoprostol is absolutely contraindicated in pregnancy—it stimulates uterine contractions and can cause abortion, miscarriage, fetal defects, and bleeding. Women of childbearing age must use reliable contraception.",
          "Misoprostol is more likely to cause diarrhea, not constipation, but this is not the priority concern."
        ]
      },
      {
        "stem": "An older adult client reports daily use of aluminum hydroxide for GERD symptoms. The nurse should assess the client for which condition?",
        "options": [
          "Diarrhea",
          "Constipation",
          "Hyperphosphatemia",
          "Hypomagnesemia"
        ],
        "answer": 1,
        "explanations": [
          "Diarrhea is associated with magnesium-containing antacids, not aluminum.",
          "Aluminum-containing antacids cause constipation. The memory aid is 'Aluminum = constipation' while 'Magnesium = diarrhea.'",
          "Aluminum causes hypophosphatemia (aluminum binds to phosphate, preventing absorption), not hyperphosphatemia.",
          "Hypomagnesemia is not a typical concern with aluminum hydroxide."
        ]
      },
      {
        "stem": "A client with H. pylori infection is prescribed bismuth-based quadruple therapy. Which combination of medications should the nurse expect?",
        "options": [
          "Omeprazole, amoxicillin, and clarithromycin",
          "Bismuth subsalicylate, tetracycline, metronidazole, and a PPI",
          "Famotidine, ampicillin, ciprofloxacin, and bismuth",
          "Sucralfate, vancomycin, metronidazole, and a PPI"
        ],
        "answer": 1,
        "explanations": [
          "This is standard triple therapy (a PPI plus two antibiotics), not quadruple therapy.",
          "Bismuth-based quadruple therapy consists of bismuth subsalicylate (coats the stomach, antimicrobial effect), tetracycline (antibiotic), metronidazole (antibiotic), and a proton pump inhibitor.",
          "This combination is not a recognized H. pylori regimen; ciprofloxacin and ampicillin are not standard agents here.",
          "Sucralfate and vancomycin are not part of H. pylori treatment protocols."
        ]
      },
      {
        "stem": "A client taking bismuth subsalicylate for H. pylori treatment calls the clinic concerned about black discoloration of the tongue and stool. What is the nurse's best response?",
        "options": [
          "Stop the medication immediately and come to the clinic",
          "This is a sign of GI bleeding; go to the emergency department",
          "This is a harmless and expected effect of the medication",
          "Reduce the dose by half and monitor for improvement"
        ],
        "answer": 2,
        "explanations": [
          "There is no need to stop the medication—these are expected effects.",
          "This is not GI bleeding; true melena has a tarry consistency and distinct odor. Bismuth simply causes harmless discoloration.",
          "Black tongue and black stools are harmless, expected side effects of bismuth subsalicylate. The client should continue the medication as prescribed.",
          "Dose adjustment is not needed for this expected side effect."
        ]
      },
      {
        "stem": "A client with peptic ulcer disease suddenly develops severe, sharp epigastric pain with a rigid, board-like abdomen. What complication should the nurse suspect?",
        "options": [
          "Gastric outlet obstruction",
          "Upper GI hemorrhage",
          "Perforation with peritonitis",
          "Acute pancreatitis"
        ],
        "answer": 2,
        "explanations": [
          "Gastric outlet obstruction presents with abdominal distention and vomiting of gastric contents, not a rigid abdomen.",
          "GI hemorrhage presents with hematemesis, melena, or signs of hypovolemia—not a rigid abdomen.",
          "Sudden severe pain with rigid, board-like abdomen indicates perforation—the ulcer has eroded through the stomach/duodenal wall, leaking contents into the peritoneal cavity causing peritonitis. This is a surgical emergency.",
          "While pancreatitis causes severe pain, it does not typically cause the board-like rigidity seen with peritonitis from perforation."
        ]
      },
      {
        "stem": "A client is prescribed cimetidine and warfarin. Which nursing action is most appropriate?",
        "options": [
          "Administer the medications together without concern",
          "Monitor for increased anticoagulant effects and signs of bleeding",
          "Hold the cimetidine until warfarin is discontinued",
          "Administer the medications 4 hours apart"
        ],
        "answer": 1,
        "explanations": [
          "Cimetidine significantly interacts with warfarin by inhibiting its metabolism—this combination requires careful monitoring.",
          "Cimetidine inhibits hepatic cytochrome P450 enzymes, which enhances the effects of medications metabolized by the liver including warfarin, phenytoin, theophylline, and benzodiazepines. The nurse must monitor for increased bleeding risk.",
          "There is no need to hold cimetidine, but close monitoring for bleeding is essential. Consider switching to famotidine, which has minimal drug interactions.",
          "Timing separation does not prevent this interaction since it involves hepatic metabolism, not GI absorption."
        ]
      },
      {
        "stem": "An older adult client taking cimetidine reports confusion and seems disoriented. The nurse recognizes this as which type of adverse effect?",
        "options": [
          "Allergic reaction",
          "Central nervous system adverse effect",
          "Serotonin syndrome",
          "Drug toxicity from overdose"
        ],
        "answer": 1,
        "explanations": [
          "Confusion is not typically a sign of allergic reaction, which would present with rash, itching, or anaphylaxis.",
          "Cimetidine crosses the blood-brain barrier and can cause CNS effects including confusion, delirium, dizziness, and mental status changes, especially in older adults. Famotidine is preferred in elderly patients because it has fewer CNS effects.",
          "Serotonin syndrome presents with hyperthermia, agitation, tremor, and hyperreflexia—not isolated confusion.",
          "This is a known side effect at therapeutic doses in susceptible populations, not necessarily overdose."
        ]
      },
      {
        "stem": "A client with chronic GERD asks why the provider is concerned about their condition. Which response by the nurse is most accurate?",
        "options": [
          "GERD can lead to stomach cancer if untreated",
          "Chronic acid exposure can cause Barrett's esophagus, which increases esophageal cancer risk",
          "Reflux symptoms are an early stage of peptic ulcer disease",
          "The acid will eventually erode through the esophageal wall"
        ],
        "answer": 1,
        "explanations": [
          "GERD affects the esophagus and increases esophageal cancer risk, not stomach cancer.",
          "Chronic GERD can lead to Barrett's esophagus—a precancerous condition where esophageal cells transform to resemble intestinal cells (metaplasia). This significantly increases the risk of esophageal cancer, which has only a 20% five-year survival rate.",
          "GERD and PUD are different conditions with different pathophysiology—reflux is not an early stage of ulcer disease.",
          "Erosion through the esophageal wall is not a typical progression of GERD."
        ]
      },
      {
        "stem": "A client with severe burn injuries is receiving esomeprazole. The nurse explains that this medication is prescribed for which purpose?",
        "options": [
          "To stimulate intestinal movement for nutrition",
          "To treat infection caused by the burns",
          "To prevent stress ulcers resulting from physiologic stress",
          "To help absorb other prescribed medications"
        ],
        "answer": 2,
        "explanations": [
          "PPIs do not stimulate intestinal motility.",
          "PPIs are not antibiotics and do not treat infection.",
          "Patients with severe physiologic stress (major trauma, burns, shock, sepsis) are at high risk for stress ulcers. PPIs or H2 blockers are given prophylactically to prevent stress ulcer formation.",
          "PPIs actually can impair absorption of certain nutrients and medications."
        ]
      },
      {
        "stem": "A client asks why they need to avoid NSAIDs after being diagnosed with gastritis. Which explanation by the nurse is correct?",
        "options": [
          "NSAIDs increase acid production in the stomach",
          "NSAIDs block prostaglandins needed for the protective mucus layer",
          "NSAIDs directly irritate the esophagus",
          "NSAIDs slow gastric emptying"
        ],
        "answer": 1,
        "explanations": [
          "NSAIDs don't directly increase acid production—they reduce protective factors.",
          "NSAIDs block COX-1, which inhibits prostaglandin synthesis. Prostaglandins are needed for secretion of protective mucus, bicarbonate, and maintaining blood supply to the mucosal layer. Without these protections, the stomach lining is vulnerable to acid damage.",
          "NSAIDs primarily affect the stomach lining, not the esophagus.",
          "NSAIDs do not affect gastric emptying in a clinically significant way related to ulcer formation."
        ]
      },
      {
        "stem": "A client with GERD asks the nurse about lifestyle changes to reduce symptoms. Which instructions should the nurse include? Select all that apply.",
        "options": [
          "Elevate the head of the bed 6-8 inches",
          "Avoid eating 2-3 hours before lying down",
          "Wear loose-fitting clothing around the abdomen",
          "Lie flat after meals to promote digestion",
          "Limit caffeine, chocolate, and fatty foods"
        ],
        "answer": [
          0,
          1,
          2,
          4
        ],
        "explanations": [
          "Correct—gravity helps prevent acid reflux into the esophagus.",
          "Correct—eating before lying down increases reflux risk.",
          "Correct—tight clothing increases intra-abdominal pressure, worsening GERD.",
          "Lying flat after meals worsens GERD by allowing acid to reflux into the esophagus. Clients should remain upright.",
          "Correct—caffeine, chocolate, and fatty foods relax the lower esophageal sphincter and increase reflux."
        ],
        "type": "sata"
      },
      {
        "stem": "A client with peptic ulcer disease vomits material that appears dark brown with a granular texture resembling coffee grounds. The nurse interprets this finding as indicating:",
        "options": [
          "Bright red blood from active rapid bleeding",
          "Digested blood from slower upper GI bleeding",
          "Bile from intestinal obstruction",
          "Normal gastric contents after eating chocolate"
        ],
        "answer": 1,
        "explanations": [
          "Bright red blood indicates fresh, active bleeding—not digested blood with a coffee-ground appearance.",
          "Coffee-ground emesis indicates blood that has been in contact with gastric acid long enough to be partially digested, turning it dark brown. This suggests slower upper GI bleeding rather than rapid hemorrhage.",
          "Bile is typically green or yellow, not dark brown and granular.",
          "Coffee-ground appearance is a clinical term for digested blood, not related to food consumption."
        ]
      },
      {
        "stem": "A client is scheduled for a urea breath test to detect H. pylori infection. The nurse explains that a positive result occurs when:",
        "options": [
          "The client experiences abdominal pain after ingesting the test solution",
          "Labeled carbon dioxide is detected in the exhaled breath",
          "The urine changes color after the test",
          "Blood pressure drops after ingesting the radioactive substance"
        ],
        "answer": 1,
        "explanations": [
          "Abdominal pain is not part of the test interpretation—the test measures exhaled gases.",
          "In the urea breath test, the client ingests carbon-labeled urea (usually non-radioactive carbon-13, or less commonly carbon-14). If H. pylori is present, its urease enzyme breaks down the urea, releasing labeled CO2 that is detected in exhaled breath.",
          "Urine testing is not part of the urea breath test; it measures exhaled carbon dioxide.",
          "Blood pressure changes are not associated with this diagnostic test."
        ]
      },
      {
        "stem": "A client reports waking up at night with burning epigastric pain that is relieved by eating crackers. These symptoms are most consistent with:",
        "options": [
          "Gastric ulcer",
          "Duodenal ulcer",
          "Acute gastritis",
          "Gastroesophageal reflux disease"
        ],
        "answer": 1,
        "explanations": [
          "Gastric ulcer pain is worsened by food, not relieved by it.",
          "Nighttime awakening with pain relieved by food is classic for duodenal ulcer. Pain occurs when the stomach is empty (2-3 hours after eating or at night), and food/antacids provide relief by absorbing acid.",
          "Acute gastritis typically presents with nausea, vomiting, and upset stomach—not pain relieved by eating.",
          "GERD symptoms are typically worsened by lying down, not specifically relieved by eating."
        ]
      },
      {
        "stem": "A client takes both aluminum hydroxide and levothyroxine daily. Which instruction is most important for the nurse to provide?",
        "options": [
          "Take both medications together with breakfast",
          "Separate the medications by at least 4 hours",
          "Take the antacid only at bedtime",
          "Discontinue the antacid while taking levothyroxine"
        ],
        "answer": 1,
        "explanations": [
          "Taking together would decrease levothyroxine absorption, potentially causing hypothyroid symptoms.",
          "Antacids can bind to and decrease absorption of many oral medications including levothyroxine, tetracyclines, and fluoroquinolones. The levothyroxine label directs separating it from aluminum- and magnesium-containing antacids by at least 4 hours to prevent this interaction.",
          "Timing at bedtime alone doesn't address the interaction if levothyroxine is taken at another time without separation.",
          "Discontinuation is not necessary—proper timing separation resolves the interaction."
        ]
      },
      {
        "stem": "A nurse is assessing a client with suspected peptic ulcer disease. Which assessment finding would indicate possible perforation requiring immediate intervention?",
        "options": [
          "Intermittent epigastric pain that improves with antacids",
          "Mild tenderness to palpation in the upper abdomen",
          "Rebound tenderness and involuntary guarding",
          "Reports of occasional heartburn after meals"
        ],
        "answer": 2,
        "explanations": [
          "Pain relieved by antacids suggests uncomplicated ulcer disease, not perforation.",
          "Mild tenderness is expected with PUD and does not indicate perforation.",
          "Rebound tenderness (pain when pressure is released) and involuntary guarding (rigid abdomen) are signs of peritoneal irritation from perforation. This is a surgical emergency requiring immediate intervention.",
          "Occasional heartburn suggests GERD, not perforation."
        ]
      },
      {
        "stem": "A client has been taking omeprazole for 4 weeks with good symptom control. The provider recommends transitioning to famotidine for maintenance therapy. The nurse explains this change is recommended because:",
        "options": [
          "Famotidine is more effective than omeprazole",
          "Long-term PPI use is associated with significant complications",
          "H2 blockers work faster than PPIs",
          "Famotidine is less expensive than omeprazole"
        ],
        "answer": 1,
        "explanations": [
          "PPIs are actually more potent acid suppressors than H2 blockers—they reduce gastric acid output by roughly 95-99%.",
          "Prescribed PPI courses for GERD are typically 4-8 weeks. Once symptoms are controlled, guidelines favor stepping down to the lowest effective therapy, such as an H2 blocker, because prolonged uninterrupted PPI use is associated with C. diff infection, fractures/osteoporosis, vitamin B12 and iron deficiency, hypomagnesemia, and pneumonia.",
          "PPIs take several days to work while H2 blockers can be used PRN, but speed isn't the reason for switching.",
          "Cost considerations may exist but safety concerns are the primary reason for limiting PPI duration."
        ]
      },
      {
        "stem": "A client with severe, refractory GERD that has not responded to medical management is scheduled for a Nissen fundoplication. The nurse explains that this procedure involves:",
        "options": [
          "Removing the lower portion of the esophagus",
          "Wrapping the stomach fundus around the lower esophagus to strengthen the sphincter",
          "Inserting a stent to keep the esophagus open",
          "Cutting the vagus nerve to reduce acid production"
        ],
        "answer": 1,
        "explanations": [
          "Esophageal resection is not part of fundoplication; the procedure reinforces, not removes, structures.",
          "Nissen fundoplication involves wrapping the upper portion of the stomach (fundus) around the lower esophagus to reinforce the lower esophageal sphincter and prevent acid reflux.",
          "Stent placement is used for strictures or obstruction, not GERD management.",
          "Vagotomy (cutting the vagus nerve) was a historical ulcer treatment, not a GERD procedure."
        ]
      },
      {
        "stem": "A pregnant client reports worsening heartburn symptoms. The nurse understands that pregnancy contributes to GERD through which mechanism?",
        "options": [
          "Increased stomach acid production during pregnancy",
          "Increased abdominal pressure from the growing uterus",
          "Decreased saliva production during pregnancy",
          "Changes in dietary preferences"
        ],
        "answer": 1,
        "explanations": [
          "Pregnancy does not significantly increase acid production; the mechanism is increased pressure and hormonal LES relaxation.",
          "The growing uterus increases intra-abdominal pressure, which compresses the stomach and forces gastric contents upward through a weakened lower esophageal sphincter. Pregnancy hormones also relax the LES.",
          "Saliva changes are not the primary mechanism of pregnancy-related GERD.",
          "While diet may change, the primary mechanism is mechanical pressure and hormonal effects on the LES."
        ]
      },
      {
        "stem": "A client with chronic kidney disease asks about taking magnesium hydroxide for occasional heartburn. What is the nurse's best response?",
        "options": [
          "This is a safe option for occasional use",
          "Magnesium-containing antacids should be avoided due to risk of hypermagnesemia",
          "Take half the recommended dose to be safe",
          "Magnesium antacids are preferred in kidney disease"
        ],
        "answer": 1,
        "explanations": [
          "Occasional use is still risky in kidney disease due to impaired magnesium excretion.",
          "Clients with kidney disease cannot efficiently excrete magnesium, leading to dangerous accumulation (hypermagnesemia) which can cause cardiac arrhythmias, hypotension, and respiratory depression. Magnesium-containing antacids should be avoided.",
          "Even reduced doses can accumulate dangerously when kidneys cannot excrete magnesium properly.",
          "Magnesium antacids are contraindicated, not preferred, in kidney disease."
        ]
      },
      {
        "stem": "A client with a history of gastric ulcers is being discharged on sucralfate. Which statement indicates the client needs additional teaching?",
        "options": [
          "I will take this medication on an empty stomach",
          "I should take my antacid at the same time for better protection",
          "I understand this medication coats my ulcer like a bandage",
          "I will take this medication before meals"
        ],
        "answer": 1,
        "explanations": [
          "Correct understanding—sucralfate should be taken on an empty stomach.",
          "Incorrect—this indicates need for teaching; antacids interfere with sucralfate activation.",
          "Correct understanding—sucralfate works by physically coating and protecting the ulcer.",
          "Correct understanding—taking before meals on an empty stomach is appropriate."
        ]
      },
      {
        "stem": "Which client is at highest risk for developing peptic ulcer disease?",
        "options": [
          "A 25-year-old who drinks one glass of wine weekly",
          "A 60-year-old taking daily ibuprofen for arthritis",
          "A 35-year-old who eats spicy food frequently",
          "A 45-year-old who drinks two cups of coffee daily"
        ],
        "answer": 1,
        "explanations": [
          "Occasional alcohol use is not a major risk factor for PUD.",
          "Long-term NSAID use (including ibuprofen) is a leading cause of peptic ulcer disease. NSAIDs block COX-1, reducing protective prostaglandins in the gastric mucosa. Older adults are especially susceptible to NSAID-induced ulcers.",
          "Spicy food may worsen symptoms but does not cause ulcers.",
          "Moderate caffeine intake is not a significant PUD risk factor."
        ]
      }
    ],
    "lower-gi": [
      {
        "stem": "A nurse is teaching a client scheduled for a colonoscopy. Which statement by the client indicates a need for further teaching?",
        "options": [
          "I will drink only clear liquids the day before the test",
          "I should stop taking aspirin one week before the procedure",
          "I can drive myself home after the procedure",
          "I will need to complete the bowel preparation as prescribed"
        ],
        "answer": 2,
        "explanations": [
          "Clear liquid diet the day before is correct preparation.",
          "Stopping aspirin to reduce bleeding risk is appropriate.",
          "Sedation is used during colonoscopy, so the client cannot drive afterward. This statement shows misunderstanding and requires clarification.",
          "Completing bowel prep is essential for adequate visualization."
        ]
      },
      {
        "stem": "A client with a new colostomy asks why the stoma appears beefy red and swollen. Which response by the nurse is most appropriate?",
        "options": [
          "The stoma is necrotic and the surgeon should be notified immediately",
          "This is expected in the immediate postoperative period due to surgical manipulation",
          "You are having an allergic reaction to the ostomy appliance",
          "This indicates an obstruction and you should not eat anything"
        ],
        "answer": 1,
        "explanations": [
          "A necrotic stoma would appear dusky, blue, or black—not red.",
          "A beefy red, edematous stoma is normal postoperatively due to surgical manipulation. It will shrink over 6-8 weeks.",
          "Allergic reaction would show on the peristomal skin, not the stoma itself.",
          "There are no signs of obstruction described in this scenario."
        ]
      }
    ],
    "neoplasms-cancer": [
      {
        "stem": "A client receiving chemotherapy has a platelet count of 18,000/mm³. Which intervention should the nurse include in the plan of care?",
        "options": [
          "Place the client in protective isolation",
          "Avoid intramuscular injections and use a soft toothbrush",
          "Encourage increased oral fluid intake",
          "Administer prescribed colony-stimulating factors"
        ],
        "answer": 1,
        "explanations": [
          "Protective isolation is for neutropenia, not thrombocytopenia.",
          "A platelet count below 20,000/mm³ indicates severe thrombocytopenia with high bleeding risk. Avoiding IM injections and trauma is essential.",
          "Fluids are important but don't address the bleeding risk priority.",
          "Colony-stimulating factors stimulate WBCs, not platelets. Thrombopoietin agents would be used for platelets."
        ]
      },
      {
        "stem": "A nurse is caring for a client receiving radiation therapy to the chest. Which finding requires immediate intervention?",
        "options": [
          "Fatigue that worsens as treatment progresses",
          "Dry, reddened skin over the treatment area",
          "Moist desquamation with open areas on the skin",
          "Temporary hair loss in the treatment field"
        ],
        "answer": 2,
        "explanations": [
          "Fatigue is an expected side effect of radiation therapy.",
          "Dry erythema is common and managed with routine skin care.",
          "Moist desquamation with open areas indicates severe skin breakdown requiring immediate intervention to prevent infection and promote healing.",
          "Hair loss in the treatment field is expected and temporary."
        ]
      }
    ],
    "neuro": [
      {
        "stem": "A client is prescribed phenytoin for seizure management. Which instruction should the nurse include in discharge teaching?",
        "options": [
          "Stop taking the medication when seizures are controlled for 6 months",
          "Report signs of gingival hyperplasia to the provider",
          "Take the medication with antacids to reduce GI upset",
          "Expect drowsiness to resolve within the first week"
        ],
        "answer": 1,
        "explanations": [
          "Anticonvulsants should never be stopped abruptly—this can trigger status epilepticus.",
          "Gingival hyperplasia is a common side effect of phenytoin that requires monitoring and dental care. The client should report this finding.",
          "Antacids decrease phenytoin absorption and should be separated from the dose.",
          "CNS effects may persist and require dosage adjustment, not just time."
        ]
      },
      {
        "stem": "A nurse is assessing a client experiencing a tonic-clonic seizure. Which action should the nurse take during the seizure?",
        "options": [
          "Insert a padded tongue blade between the teeth",
          "Restrain the client's extremities to prevent injury",
          "Turn the client to the side and protect the head",
          "Begin rescue breathing immediately"
        ],
        "answer": 2,
        "explanations": [
          "Never insert anything into the mouth during a seizure—risk of injury to client and nurse.",
          "Restraining extremities can cause musculoskeletal injury.",
          "Side-lying position maintains the airway and allows secretions to drain. Protecting the head from injury is the priority during an active seizure.",
          "The client is not in respiratory arrest; positioning maintains the airway adequately."
        ]
      },
      {
        "stem": "A client reports a migraine with visual aura and unilateral throbbing pain. Which intervention should the nurse anticipate?",
        "options": [
          "Administer a triptan medication as prescribed",
          "Apply a warm compress to the affected side",
          "Encourage the client to ambulate in the hallway",
          "Provide a high-protein snack"
        ],
        "answer": 0,
        "explanations": [
          "Triptans are first-line abortive therapy for migraines. They work best when given early in the attack.",
          "Cold, not warm, compresses may help—heat can worsen vasodilation and pain.",
          "A dark, quiet environment is preferred; activity can worsen symptoms.",
          "There is no indication for a high-protein snack in acute migraine management."
        ]
      }
    ]
  }
};
